# Implement your install deployment tasks here
# -------------------------------------------------

- name: install operators 
  k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - operator-template.yml.j2

- name: set default deployment name
  when: operator_deployment_name is defined
  set_fact:
    _operator_deployment_name: "{{ operator_deployment_name }}"

- name: get deployment name
  when: operator_deployment_name is undefined
  block:
    - name: get subscription info
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        namespace: "{{ operator_namespace }}"
        name: "{{ operator_subscription_name }}" 
      register: r_subscription
      retries: 30
      delay: 10
      until:
        - r_subscription.resources | length | int > 0
        - r_subscription.resources[0].status.currentCSV is defined
    - name: get CSV info
      k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: "{{ operator_namespace }}"
        name: "{{ r_subscription.resources[0].status.currentCSV }}" 
      register: r_csv
      retries: 30
      delay: 10
      until:
        - r_csv.resources | length | int > 0
        - r_csv.resources[0].spec.install.spec.deployments[0].name is defined
    - name: set deployment name
      set_fact:
        _operator_deployment_name: "{{ r_csv.resources[0].spec.install.spec.deployments[0].name }}"

- name: wait for operator to be ready
  k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ operator_namespace }}"
    name: "{{ _operator_deployment_name }}"
  register: r_deployment
  retries: 60
  delay: 10
  until:
    - r_deployment.resources | length | int > 0
    - r_deployment.resources[0].status.availableReplicas is defined
    - r_deployment.resources[0].status.availableReplicas | int == r_deployment.resources[0].spec.replicas | int
  when: wait_for_operator
  
# Leave these as the last tasks in the playbook
- name: operator install complete
  debug:
    msg: "Install operator tasks completed successfully."
  when:
    - not silent|bool

