# Implement your post-install deployment tasks here
# -------------------------------------------------
- name: create application
  k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    #- github-oauth-config.yml.j2
    - openshift-devspaces-instance.yml.j2

# Leave these as the last tasks in the playbook
- name: post_install tasks complete
  debug:
    msg: "Post-Install tasks completed successfully."
  when:
    - not silent|bool

