---
registry_superuser_username: quayadmin
registry_superuser_password: "{{ default_password }}"
registry_superuser_email: "admin@example.com"

#registry_superuser_password: "{{
#  default_password | default(lookup('password', '/dev/null chars=ascii_letters,digits '~ 'length=' ~ 10)) }}"

registry_name: "{{ idp_prefix }}-registry" # "quay-registry"
app_namespace: "{{ idp_prefix }}-quay" # "quay-enterprise"

# defaults
operator_namespace: "openshift-operators"
