# Implement your install deployment tasks here
# -------------------------------------------------
- name: running install tasks
  debug:
    msg: "Running installation tasks for {{ role_name }}"
    
- name: create operator namespace
  k8s:
    state: present
    kind: Namespace
    name: "{{ operator_namespace }}"

- name: create app namespace
  k8s:
    state: present
    kind: Namespace
    name: "{{ app_namespace }}"

- name: install operator
  include_role:
    name: roles/install_operator
  vars:
    operator_name: "rhdh"
    operator_subscription_name: "rhdh"
    operator_deployment_name: "rhdh-operator"
    subscription_channel: "fast"

# Leave these as the last tasks in the playbook
- name: install tasks complete
  debug:
    msg: "Install tasks completed successfully."
  when:
    - not silent|bool

