all:
  vars:
    # set the following to control the install/uninstall proces
    # basic developer services, SHOULD be installed by default

    install_devops: false      # Openshift GitOps / Pipelines
    install_quay: false        # Quay.io
    install_devspaces: false  # Red Hat OpenShift Dev Spaces

    # software factory services (optional & opinionated)
    install_developer_hub: true   # Red Hat Developer Hub

    # other defaults
    default_password: "admin321"
