apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-agent-injector-cfg
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNSekNDQWU2Z0F3SUJBZ0lVYXhmVVVSVWNXck5iQ2ZxWGFqOEU5alVDM1FRd0NnWUlLb1pJemowRUF3SXcKR2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUI0WERUSXpNREV5TnpBd01EUXhNMW9YRFRNegpNREV5TkRBd01EVXhNMW93R2pFWU1CWUdBMVVFQXhNUFFXZGxiblFnU1c1cVpXTjBJRU5CTUZrd0V3WUhLb1pJCnpqMENBUVlJS29aSXpqMERBUWNEUWdBRTFmaFlWT3FBSmg3M0hudjllcXhaOS8wS09NMzFxbTVxL2l4NCtiM1EKMHFyK25jdjdSWFlYc3g1UXFkQVp3Tkpzb0NlSUs2UmdkQytNZ2JTN2dvV3AvcU9DQVJBd2dnRU1NQTRHQTFVZApEd0VCL3dRRUF3SUNoREFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvCk1HZ0dBMVVkRGdSaEJGODNZanBtTXpwbU16cGlaVHBpTlRvMFpUbzRZVG93T1RwbU1EcGhZem95TURvMlpUb3oKTmpvMU5EbzNaVHBsTURwa016cGlaam81TkRvM05UbzNOVHBpWWpvNE5qcG1Zem8zTURvM1l6b3lOVG96TmpvMgpOam95TVRvMU9UcGhPVEJxQmdOVkhTTUVZekJoZ0Y4M1lqcG1NenBtTXpwaVpUcGlOVG8wWlRvNFlUb3dPVHBtCk1EcGhZem95TURvMlpUb3pOam8xTkRvM1pUcGxNRHBrTXpwaVpqbzVORG8zTlRvM05UcGlZam80TmpwbVl6bzMKTURvM1l6b3lOVG96TmpvMk5qb3lNVG8xT1RwaE9UQUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQkNCeUFZcDZPeApHNEYyQ015ZjJDQ3lSM2NBT2RMUEoxamJBMXV6ZW1lODlnSWdia2RuTHk2WGhyWjcvbmgyZVpqME8yZ3dGUk1xCk51QVZlVzBaWXcxMTNGYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ1NEQ0NBZTZnQXdJQkFnSVVVdE5pT0hJTDB3NFRqa1paMXVDenMwQzc4dVF3Q2dZSUtvWkl6ajBFQXdJdwpHakVZTUJZR0ExVUVBeE1QUVdkbGJuUWdTVzVxWldOMElFTkJNQjRYRFRJek1ERXlOekF3TWpJMU1Wb1hEVE16Ck1ERXlOREF3TWpNMU1Wb3dHakVZTUJZR0ExVUVBeE1QUVdkbGJuUWdTVzVxWldOMElFTkJNRmt3RXdZSEtvWkkKemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNVVlTUlFRFRSNDlITlk4Q01ELzBDRFlXRmJKbjRNNU4vcTRqdTg2ZgpzaW9YdmorWkdjTmpmZmFReENhTXI5U1hiVkQrdlljYVNoeHlGMm1vaStXZkJhT0NBUkF3Z2dFTU1BNEdBMVVkCkR3RUIvd1FFQXdJQ2hEQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC8KTUdnR0ExVWREZ1JoQkY4eVpqbzFOenBqTWpvMk5UbzFaRG95WlRvNVpUcGxaVHBsWXpveE5EbzJOam95TURvMgpNam80TWpvMk1qcG1Nam8xTkRwbVlUb3dZVHBsWmpvNFpUb3hNenBsWmpvd056b3laVG8zTmpvMU1qcGhZem95Ck16bzVaanBpWlRwa1pEQnFCZ05WSFNNRVl6QmhnRjh5WmpvMU56cGpNam8yTlRvMVpEb3laVG81WlRwbFpUcGwKWXpveE5EbzJOam95TURvMk1qbzRNam8yTWpwbU1qbzFORHBtWVRvd1lUcGxaam80WlRveE16cGxaam93TnpveQpaVG8zTmpvMU1qcGhZem95TXpvNVpqcGlaVHBrWkRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCL2U5N1Z0Zjk4Cm9UbS9vK0FiUnFJRDFQK1RHOUdJT2FiMXF2M2RJOWZUK3dJaEFPWmpRRmg5WFp1Uzc0d0FMZmFJMkRZQ012dmYKd0VLLzUxc2VlOXdPRExFNQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: vault-agent-injector-svc
      namespace: vault
      path: /mutate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: vault.hashicorp.com
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - vault-agent-injector
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
