- name: Install all Software Factory services
  hosts: localhost
  vars:
    # set the following to control the install/uninstall process
    silent: false
    become_override: false
    ACTION: "INSTALL" # INSTALL, UNINSTALL, UPDATE
  
  roles:
    #- role: ../roles/gitops_basics
    - role: ../roles/quay_basics
